# Generated by Django 4.2.5 on 2023-09-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('longitude_from', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=1)),
                ('latitude', models.FloatField()),
                ('latitude_from', models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('longitude_from', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=1)),
                ('latitude', models.FloatField()),
                ('latitude_from', models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1)),
                ('available', models.IntegerField()),
                ('total', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(1, 'Not Satisfied'), (2, 'Not Up to the Mark'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locality')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('license', models.CharField(max_length=15)),
                ('longitude', models.FloatField()),
                ('longitude_from', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=1)),
                ('latitude', models.FloatField()),
                ('latitude_from', models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('charging', 'Charging'), ('Gas stations', 'Gas stations')], max_length=50)),
                ('longitude', models.FloatField()),
                ('longitude_from', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=1)),
                ('latitude', models.FloatField()),
                ('latitude_from', models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1)),
                ('rating', models.IntegerField(choices=[(1, 'Not Satisfied'), (2, 'Not Up to the Mark'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=75)),
                ('password', models.CharField(max_length=100)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parking')),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='user_visited',
            field=models.ManyToManyField(to='core.user'),
        ),
        migrations.CreateModel(
            name='Local_Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('longitude_from', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=1)),
                ('latitude', models.FloatField()),
                ('latitude_from', models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1)),
                ('rating', models.IntegerField(choices=[(1, 'Not Satisfied'), (2, 'Not Up to the Mark'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('type', models.CharField(choices=[('food', 'food'), ('grocery', 'grocery'), ('Chemist', 'Chemist')], max_length=25)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locality')),
            ],
        ),
    ]
